version: '3'

services:
  web:
    build: .
    container_name: ocap-web
    ports:
      - "8000:8000"
    volumes:
      - captures:/app/static/captures/
      - database:/app/database/
      - maps:/app/static/images/maps/

volumes:
  captures:
  database:
  maps: